### ISSUE TITLE
What is the best way to expose our own Custom Customer fields?

### ISSUE THREAD

**Issue by MikeOtown** [oroinc/magento-orocrm-bridge#10]
What is the best way to expose our own Custom Customer fields?

**Comment by sergeyz** [comment]
@MikeOtown check this one https://github.com/orocrm/crm/blob/master/src/Oro/Bundle/MagentoBundle/Resources/doc/reference/eav_attributes_support.md#magento-eav-attributes-support

**Comment by MikeOtown** [comment]
Thank you.  Question about the last part of these instructions...

> After performing of this steps EAV attributes exposed to Oro. Them are mapped to entity fields by name...

Do I now need to create a Bundle that adds new Customer Entity fields?

**Comment by sergeyz** [comment]
You can do it [from UI also](https://www.orocrm.com/documentation/index/current/user-guide/entity-fields)

**Comment by MikeOtown** [comment]
In our Magento site backend, I turned on “Enable Additional Attributes” in System->Configuration->Customers->OroCRM. Now, in SoapUI oroCustomerList returns an empty `<attributes/>` tag for each Customer and oroCustomerInfo returns:

 `<attributes>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
               <complexObjectArray/>
            </attributes>`

What could be the issue? Why are our custom attributes not being returned?

**Comment by MikeOtown** [comment]
What is the best way to debug this extension?  Where should I put breakpoints?  Is there a way to turn on Verbose logging?

**Comment by sergeyz** [comment]
Looks like here https://github.com/orocrm/magento-orocrm-bridge/blob/master/app/code/community/Oro/Api/Helper/Data.php#L186

**Comment by MikeOtown** [comment]
I keep getting...

> [11-Jan-2017 14:33:01 UTC] PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost:8088/index.php/api/v2_soap/index/?XDEBUG_SESSION_START=netbeans-xdebug&wsdl=1' : failed to load external entity "http://localhost:8088/index.php/api/v2_soap/index/?XDEBUG_SESSION_START=netbeans-xdebug&wsdl=1"

Fails when I add the XDEBUG_SESSION_START parameter.  Does anyone successfully debug SOAP calls from phpStorm?

**Comment by sergeyz** [comment]
AFAIK, you have to set breakpoint once request started. Breakpoint before request stops SOAP request somehow.

**Comment by vbyndych** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
