### ISSUE TITLE
Add composer installation

### ISSUE THREAD

**Issue by sagikazarmark** [oroinc/magento-orocrm-bridge#2]
It would really be nice if this package could be installed with composer.

References:

https://github.com/Cotya/magento-composer-installer
https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/MakeAModuleInstallableWithComposer.md

Would you accept a PR for that?

**Comment by sagikazarmark** [comment]
PR #3 sent.

**Comment by alex-n-2k7** [comment]
@sagikazarmark  I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.

duplicated by https://github.com/oroinc/magento-orocrm-tracking/issues/2
internal task to fix this problem (Internal ID: CRM-8470)
