### ISSUE TITLE
Procedure 'oroPing' not present in /var/www/magento/lib/Zend/Soap/Server.php on line 889

### ISSUE THREAD

**Issue by ghost** [oroinc/magento-orocrm-bridge#6]
After setting up OroCRM Bridge v1.1.4.3 integration with Magento 1.9.2.4 CE and configuring a integration in OroCRM 1.9.6, i see the following error spike up in the error-log:

```
2016/07/21 23:10:06 [error] 3413#3413: *180955 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Procedure 'oroPing' not present in /var/www/magento/lib/Zend/Soap/Server.php on line 889" while reading response header from upstream, client: x.x.x.x, server: hafner-ips.com, request: "POST /index.php/api/v2_soap/index/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "www.myshop.com"
```

The module provides all the soap methods as expected,  snippet from /api/v2_soap/?wsdl=1

```
<operation name="oroPing"><documentation>Get basic presence info</documentation><input message="typens:oroPingRequest"/><output message="typens:oroPingResponse"/></operation>
```

I've already checked the SOAP API user credentials, role and permissions and recreated them but without success. Within OroCRM inside the integration configuration it says "Native Magento API is used; only customers and orders will be synced" - i dunno why.

Any hints?

Thanks

**Comment by sergeyz** [comment]
Hi, @schallertd, please use new bridge version (its 1.2.5.0) from https://www.magentocommerce.com/magento-connect/orocrm-bridge.html

**Comment by alex-n-2k7** [comment]
@ghost, I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
